CI: don't fetch tags with the first `git fetch`
While it would be ideal to fetch all tags alongside the current
commit/branch that we are testing, the `checkout` action runs the
following command when a commit coincides with a tag:

git fetch origin [...] +[hash]:refs/tags/[tag]

which fails with the following error:

Error: fatal: Cannot fetch both [hash] and refs/tags/[tag] to
refs/tags/[tag]

Which can be explained as the `checkout` action instructing git to save
the current commit to the tag, whilst git is also attempting to fetch
the same tag, resulting in the conflict.